# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'name.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelbutton = QtWidgets.QPushButton(self.centralwidget , clicked= lambda : self.nameBTN_clicked())
        self.labelbutton.setGeometry(QtCore.QRect(150, 30, 441, 221))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(28)
        self.labelbutton.setFont(font)
        self.labelbutton.setObjectName("labelbutton")
        self.namelabel = QtWidgets.QLabel(self.centralwidget)
        self.namelabel.setGeometry(QtCore.QRect(150, 310, 481, 161))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(28)
        self.namelabel.setFont(font)
        self.namelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.namelabel.setObjectName("namelabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMyname = QtWidgets.QMenu(self.menubar)
        self.menuMyname.setObjectName("menuMyname")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMyname.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def nameBTN_clicked(self):
        self.namelabel.setText("My name is Rahms")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelbutton.setText(_translate("MainWindow", "Want to know my name?"))
        self.namelabel.setText(_translate("MainWindow", "I am..."))
        self.menuMyname.setTitle(_translate("MainWindow", "Myname"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
